### ISSUE TITLE
Collapsing box & reopening makes it disappear on scroll

### ISSUE THREAD

**Issue by andrearennick** [norcross/sticky-publish-box#1]
If the publish box is collapsed for any reason, then re-opened, scrolling down continues to grey out the rest of the meta boxes, but the Publish box fails to appear.

This is in Chrome on a Mac.  

On a new post, it works fine. Also, it goes back to working properly on a page reload.

**Comment by norcross** [comment]
@andrearennick can you pull the updated version (the two JS files) and test it again?

**Comment by andrearennick** [comment]
Looks like that did the trick!  THANKS! :+1:
